/**
 * Game Registry - Centralized plug-and-play game catalog.
 * Complete 16-game catalog categorized for mobile-first filtering and search.
 */

export const CATEGORIES = [
  'All Games',
  'Board',
  'Arcade',
  'Puzzle',
  'Sports',
  'Classic',
  'Multiplayer'
];

export const GAME_REGISTRY = [
  {
    id: 'ludo',
    title: 'Ludo Classic',
    shortName: 'Ludo',
    category: 'Board',
    secondaryCategories: ['Multiplayer', 'Classic'],
    entryFee: 100,
    winReward: 180,
    status: 'active',
    badge: 'Popular',
    badgeColor: 'amber',
    iconName: 'Dices',
    description: 'The beloved classic cross-and-circle board game. Roll the dice, move your tokens, and race home!',
    features: ['1v1 vs Bot', '3D Dice Pips', 'Touch Controls', 'Safe Zones']
  },
  {
    id: 'carrom',
    title: 'Carrom Clash',
    shortName: 'Carrom',
    category: 'Sports',
    secondaryCategories: ['Classic', 'Multiplayer'],
    entryFee: 50,
    winReward: 90,
    status: 'active',
    badge: 'Hot',
    badgeColor: 'amber',
    iconName: 'Target',
    description: 'Classic Carrom board showdown. Position your striker, line up your angle, and pocket the queen!',
    features: ['1v1 Board', 'Striker Physics', 'Pocket Scoring', 'Queen Bonus']
  },
  {
    id: 'chess',
    title: 'Chess Master',
    shortName: 'Chess',
    category: 'Classic',
    secondaryCategories: ['Board', 'Multiplayer'],
    entryFee: 60,
    winReward: 110,
    status: 'active',
    badge: 'Strategy',
    badgeColor: 'indigo',
    iconName: 'Trophy',
    description: 'Timeless 8x8 tactical battle. Outmaneuver your opponent with piece captures and checkmate.',
    features: ['8x8 Grid', 'Bot Opponent', 'Touch Selection', 'Capture Points']
  },
  {
    id: 'pool',
    title: '8 Ball Pool',
    shortName: '8 Ball Pool',
    category: 'Sports',
    secondaryCategories: ['Arcade'],
    entryFee: 60,
    winReward: 110,
    status: 'active',
    badge: 'Featured',
    badgeColor: 'emerald',
    iconName: 'Circle',
    description: 'Smooth green-felt billiards simulation. Aim your cue stick, adjust power, and sink the 8-ball.',
    features: ['6 Pockets', 'Cue Ball Physics', 'Angle Meter', 'Combo Pots']
  },
  {
    id: 'knife-target',
    title: 'Knife Target Hit',
    shortName: 'Knife Target',
    category: 'Arcade',
    secondaryCategories: [],
    entryFee: 40,
    winReward: 75,
    status: 'active',
    badge: 'Fast',
    badgeColor: 'rose',
    iconName: 'Zap',
    description: 'Arcade timing test. Tap to fling blades into the rotating timber target without striking existing knives.',
    features: ['Rotating Log', 'Single Tap', 'Level Ramping', 'Reflex Skill']
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic-Tac-Toe Blitz',
    shortName: 'Tic-Tac-Toe',
    category: 'Board',
    secondaryCategories: ['Puzzle', 'Classic'],
    entryFee: 50,
    winReward: 90,
    status: 'active',
    badge: 'Instant Play',
    badgeColor: 'cyan',
    iconName: 'Grid',
    description: 'Fast 3x3 tactical grid showdown against an adaptive Bot. Align 3 marks before the timer expires!',
    features: ['Quick Rounds', 'Adaptive Bot', 'Instant Play', 'Win Streaks']
  },
  {
    id: 'mines',
    title: 'Minesweeper Blitz',
    shortName: 'Mines',
    category: 'Puzzle',
    secondaryCategories: ['Arcade'],
    entryFee: 30,
    winReward: 60,
    status: 'active',
    badge: 'High Stakes',
    badgeColor: 'rose',
    iconName: 'ShieldAlert',
    description: 'Uncover sparkling gems across a 4x4 grid. Avoid the 3 hidden mines or cash out your multiplier!',
    features: ['Cashout Option', 'Multiplier Ladder', 'Dynamic Grid', 'Fast Play']
  },
  {
    id: 'memory',
    title: 'Memory Match',
    shortName: 'Memory',
    category: 'Puzzle',
    secondaryCategories: ['Classic'],
    entryFee: 35,
    winReward: 65,
    status: 'active',
    badge: 'Brain',
    badgeColor: 'indigo',
    iconName: 'Brain',
    description: 'Flip and match 6 pairs of colorful gems and badges. Test your visual memory in minimal moves.',
    features: ['12 Cards', 'Flip Animations', 'Move Counter', 'Brain Trainer']
  },
  {
    id: 'connect-four',
    title: 'Connect Four',
    shortName: 'Connect 4',
    category: 'Board',
    secondaryCategories: ['Classic', 'Multiplayer'],
    entryFee: 45,
    winReward: 80,
    status: 'active',
    badge: 'Classic',
    badgeColor: 'indigo',
    iconName: 'Layers',
    description: 'Vertical 7x6 tactical grid challenge. Drop your colored discs and connect 4 in a row to triumph.',
    features: ['7x6 Board', 'Gravity Drop', 'Bot AI', 'Touch Columns']
  },
  {
    id: 'rps',
    title: 'Rock Paper Scissors',
    shortName: 'RPS Clash',
    category: 'Classic',
    secondaryCategories: ['Arcade'],
    entryFee: 25,
    winReward: 50,
    status: 'active',
    badge: 'Quick',
    badgeColor: 'amber',
    iconName: 'Hand',
    description: 'Rapid hand-sign showdown. Pick Rock, Paper, or Scissors and be the first to reach 3 match points.',
    features: ['Best of 5', 'Instant Duel', 'Bot Rival', 'Big Buttons']
  },
  {
    id: 'archery',
    title: 'Archery World',
    shortName: 'Archery',
    category: 'Sports',
    secondaryCategories: ['Arcade'],
    entryFee: 45,
    winReward: 80,
    status: 'active',
    badge: 'Skill',
    badgeColor: 'amber',
    iconName: 'Target',
    description: 'Draw your bowstring, gauge the shifting wind, and release arrows directly into the golden bullseye.',
    features: ['Moving Target', 'Bullseye Ring', 'Timing Gauge', '6 Arrows']
  },
  {
    id: 'snakes-ladders',
    title: 'Snakes & Ladders Pro',
    shortName: 'Snakes & Ladders',
    category: 'Board',
    secondaryCategories: ['Classic'],
    entryFee: 50,
    winReward: 90,
    status: 'active',
    badge: 'Classic',
    badgeColor: 'emerald',
    iconName: 'Sparkles',
    description: 'Ascend the ladders to the top, steer clear of venomous snakes, and reach tile 100 first.',
    features: ['100 Tiles', 'Dice Roller', 'Ladder Boosts', 'Bot Opponent']
  },
  {
    id: 'bubble-shooter',
    title: 'Bubble Shooter',
    shortName: 'Bubble Pop',
    category: 'Arcade',
    secondaryCategories: ['Puzzle'],
    entryFee: 40,
    winReward: 75,
    status: 'active',
    badge: 'Casual',
    badgeColor: 'cyan',
    iconName: 'CircleDot',
    description: 'Color-matching arcade challenge. Aim and launch bubbles to pop clusters of matching colors.',
    features: ['Cluster Pops', 'Color Rows', 'Aim Reticle', 'Combo Score']
  },
  {
    id: 'fruit-slice',
    title: 'Fruit Slice Blitz',
    shortName: 'Fruit Slice',
    category: 'Arcade',
    secondaryCategories: [],
    entryFee: 45,
    winReward: 80,
    status: 'active',
    badge: 'Action',
    badgeColor: 'amber',
    iconName: 'Flame',
    description: 'Swift swipe and slice arcade sensation. Slice juicy tossed watermelons and oranges in mid-air!',
    features: ['Swipe Slices', 'Combo Splashes', 'Reflex Pace', 'Blade Glow']
  },
  {
    id: 'checkers',
    title: 'Checkers Pro',
    shortName: 'Checkers',
    category: 'Classic',
    secondaryCategories: ['Board'],
    entryFee: 40,
    winReward: 75,
    status: 'active',
    badge: 'Board',
    badgeColor: 'rose',
    iconName: 'Crown',
    description: 'Diagonal jumping checkers competition. Leap over opponent pieces and crown your kings!',
    features: ['8x8 Dark Grid', 'King Crowns', 'Jump Captures', 'Touch Tiles']
  },
  {
    id: 'sudoku',
    title: 'Speed Sudoku',
    shortName: 'Sudoku',
    category: 'Puzzle',
    secondaryCategories: [],
    entryFee: 40,
    winReward: 75,
    status: 'active',
    badge: 'Numbers',
    badgeColor: 'cyan',
    iconName: 'Hash',
    description: 'Logic and number arrangement grid. Fill numbers 1-9 without duplicates in rows and columns.',
    features: ['Number Grid', 'Quick Logic', 'Error Checks', 'Clean Focus']
  }
];

export function getGameById(gameId) {
  return GAME_REGISTRY.find((g) => g.id === gameId) || null;
}
